### ISSUE TITLE
Launchpad X support

### ISSUE THREAD

**Issue by Isaiah-Sugar** [turbaszek/lss#4]
Hello! I have a launchpad x, and was able to get this working with it pretty easily. I'm not sure how you would want this implemented (if at all), so I figured I'd just explain what I changed.

-changed `def __init__(self, name: str = "Launchpad Mini MK3 LPMiniMK3 MIDI"):` to `def __init__(self, name: str = "Launchpad X LPX MIDI"):`
-changed the hex codes (to enter programmer mode) from 240 0 32 41 2 13 0 127 247  to  240 0 32 41 2 12 0 127 247  
(13 changed to 12, to match the launchpad x's programmer's reference manual)
https://fael-downloads-prod.focusrite.com/customer/prod/s3fs-public/downloads/Launchpad%20X%20-%20Programmers%20Reference%20Manual.pdf
-changed 
`    def _process_pad_message(self, msg: NoteMessage) -> None:
        if msg.velocity !=127:
            return`
to
`    def _process_pad_message(self, msg: NoteMessage) -> None:
        if msg.velocity == 0:
            return`
(launchpad x has velocity sensitivity lol. no need to beat up the pads)

**Comment by turbaszek** [comment]
Hey @Isaiah-Sugar thanks for reporting! I'm planning to add option to choose MiDI device and decouple sequencer from lunchpad model. I will keep you posted 🚀 

Btw. do you find this project useful?

**Comment by turbaszek** [comment]
Hey @Isaiah-Sugar would you mind contributing support for Launchpad X? From your description it seems that all that is required is adding new class similar to this one:
https://github.com/turbaszek/lss/blob/e55d2eba9024831dcb846aa46fd40d04b2ee9adc/lss/devices/launchpad_mini_3.py#L5-L13

Then adding the new launchpad to this dict:
https://github.com/turbaszek/lss/blob/5d5ee812f4293197d9060871f6e32a8b2851f25b/lss/devices/__init__.py#L3
